### ISSUE TITLE
Issues with 25.1.0

### ISSUE THREAD

**Issue by SpencerDepas** [DmitryMalkovich/circular-with-floating-action-button#13]
The progress bar is no longer working since I updated my dependencies to 25.1.0. I think the progress bar is under the fab and no longer the correct size. Found on a nexus 5x.

**Comment by TKolbusz** [comment]
Works fine on API 16 and 19, API 21 it doesn't show anymore, but on API 24 it works fine for me

**Comment by DmitryMalkovich** [comment]
Hello @SpencerDepas and @TKolbusz, thanks you! I will try to figure out the problem.

**Comment by TKolbusz** [comment]
@DmitryMalkovich 
I made it work, resize() is function that I added because you copied the same code twice.

```
    private void resize()
    {
        float translationZpx = getResources().getDisplayMetrics().density * 6; // 6 is needed for progress bar to be visible, 5 doesnt work
        if(Build.VERSION.SDK_INT == Build.VERSION_CODES.LOLLIPOP) mProgressBar.setTranslationZ(translationZpx);

        LayoutParams mFabParams = ((LayoutParams) mFab.getLayoutParams());
        LayoutParams mProgressParams = ((LayoutParams) mProgressBar.getLayoutParams());

        int additionSize = getResources().getDimensionPixelSize(R.dimen.progress_bar_size);
        //int additionSize = 0;

        mProgressBar.getLayoutParams().height = mFab.getHeight() + additionSize;
        mProgressBar.getLayoutParams().width = mFab.getWidth() + additionSize;

        mFabParams.gravity = Gravity.CENTER;
        mProgressParams.gravity = Gravity.CENTER;
    }
```

**Comment by DmitryMalkovich** [comment]
@TKolbusz, well done! Could you create a pull-request?

**Comment by TKolbusz** [comment]
@DmitryMalkovich I'll do that later

**Comment by hackdie** [comment]
for me works with...

`private void resize() {
        float translationZpx = getResources().getDisplayMetrics().density * 6; // 6 is needed for progress bar to be visible, 5 doesnt work
        if (Build.VERSION.SDK_INT == Build.VERSION_CODES.LOLLIPOP)
            mProgressBar.setTranslationZ(translationZpx);

        int additionSize = getResources().getDimensionPixelSize(R.dimen.progress_bar_size);

        LayoutParams parms = new LayoutParams(mFab.getWidth() + additionSize, mFab.getHeight() + additionSize);
        parms.gravity = Gravity.CENTER;
        mProgressBar.setLayoutParams(parms);
    }`
