### ISSUE TITLE
Show real progress

### ISSUE THREAD

**Issue by DmitryMalkovich** [DmitryMalkovich/circular-with-floating-action-button#3]
We can use default the circular progress bars, but this progress bar's style only supports indeterminate mode without showing real progress (incrementProgressBy() or setProgress()).

If you will use the progress bar to show real progress, you must use the horizontal bar.

We can create our own progress bar or add support of already implemented custom progress bar with needed functionalty. The third possibility is to show it via percentages (text representation) over the button.

**Comment by bachvtuan** [comment]
Hey, I get the same situation like you. Can you tell me how did you resolve this ?

**Comment by DmitryMalkovich** [comment]
My intention was to support the most popular custom progress bars (e. g https://github.com/lzyzsd/CircleProgress), it will be added quite soon!

**Comment by bachvtuan** [comment]
Thank you @DmitryMalkovich .

**Comment by roman-ku** [comment]
What is the status of this issue? Has this been added to the library?

**Comment by roman-ku** [comment]
Just tried this myself. Indeterminate progress has not been added.

**Comment by roman-ku** [comment]
Any progress on this?

**Comment by roman-ku** [comment]
@DmitryMalkovich Why is it closed? Has it been implemented?
