### ISSUE TITLE
Fab displacement and progressbar being oversized.

### ISSUE THREAD

**Issue by SpencerDepas** [DmitryMalkovich/circular-with-floating-action-button#6]
https://photos.google.com/share/AF1QipM7-H3oge9T_4zQfD-i2NEN87VNPjucDmqlHAmgF-q75NtyOMKGs-Z7qPb4I8unsw/photo/AF1QipM-UZRyrkR0ApUYHWIXCNGgvbTwdwrAxbuZ1RI3?key=VndzMFo0cUtaUmdVWXZQcnlkZWhVb0F0UWdjYkF3

    <com.dmitrymalkovich.android.ProgressFloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
        android:clickable="true">

        <android.support.design.widget.FloatingActionButton
            android:id="@+id/refresh_location_fab"
            android:src="@drawable/ic_refresh_white_48dp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            />

        <ProgressBar
            android:id="@+id/mapsAcitvityProgressBar"
            style="@style/Widget.AppCompat.ProgressBar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

    </com.dmitrymalkovich.android.ProgressFloatingActionButton>

**Comment by DmitryMalkovich** [comment]
@SpencerDepas What device did you use? Thank you!

**Comment by DmitryMalkovich** [comment]
I tested on Nexus 5x (as @SpencerDepas ) and there are no problems. Can you provide some additional information about it?

**Comment by SpencerDepas** [comment]
It happens during a map v2 camera animation. Each time the animation occurs the progress bar gets bigger and the fab moves closer to the center of the screen. I am using the library in two places. In my Fragment without the camera animation I have no issue.

**Comment by DmitryMalkovich** [comment]
I will try to reproduce the issue firstly. I will inform periodically about progress. Thank you!

**Comment by DmitryMalkovich** [comment]
Fixed in v1.4

**Comment by SpencerDepas** [comment]
Awesome.
