### ISSUE TITLE
Containing Layout

### ISSUE THREAD

**Issue by pantos27** [DmitryMalkovich/circular-with-floating-action-button#8]
I'm getting
ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.support.design.widget.CoordinatorLayout$LayoutParams

Di I have to wrap this in a CoordinatorLayout?

**Comment by DmitryMalkovich** [comment]
Hello @pantos27, thank you for writing in!
It is not so necessary, but it is required for a snackbar raising animation support for fab.

I recommend to wrap it with `CoordinatorLayout`, but i will fix it anyway in v1.6 soon.

**Comment by DmitryMalkovich** [comment]
Fixed in 1.6
